### ISSUE TITLE
Revert op-node temporary patch

### ISSUE THREAD

**Issue by nagdahimanshu** [LiskHQ/lisk-node#20]
### Description

To run Lisk nodes, a temporary patch was applied when building the `op-node` image to run Lisk nodes.
Also, in the readme is recommended to apply the path before building op-node.
This should be reverted once `systemConfig` contract is redeployed on the Lisk network.

### Acceptance Criteria

- All changes related to the patch should be reverted

**Comment by sameersubudhi** [comment]
The SystemConfig contract won't be redeployed on Lisk Sepolia.
Lisk will continue to use the op-node patch. Closing the issue.

This information has been added to the repo with https://github.com/LiskHQ/lisk-node/pull/31.
