### ISSUE TITLE
Update reth client profile to maxperf

### ISSUE THREAD

**Issue by nagdahimanshu** [LiskHQ/lisk-node#9]
### Description
Currently, to build `reth` client docker image, profile is set to `release`.
But for maximum performance,  profile should be `maxperf` but it throws error currently.

### Acceptance Criteria

- Update profile to `maxperf`
- Docker image should build without any issue

**Comment by Oyase-shinobi** [comment]
Hello @sameersubudhi @nagdahimanshu 
I have checked this project and very interested in
I would love to engage in your team and contribute in this project

**Comment by sameersubudhi** [comment]
Hello @Oyase-shinobi,

Thank you for showing your interest. You can always contribute via PRs to any of our open-source projects at will.
In case you're looking for a full-time engagement with us, currently we do not have any openings in the team. Please keep an eye on https://lightcurve.jobs.personio.de for any open opportunities with Lisk in the future.

Best regards,
Sameer

**Comment by sameersubudhi** [comment]
Addressed with #38.

**Comment by Oyase-shinobi** [comment]
> Hello @Oyase-shinobi,
> 
> Thank you for showing your interest. You can always contribute via PRs to any of our open-source projects at will. In case you're looking for a full-time engagement with us, currently we do not have any openings in the team. Please keep an eye on https://lightcurve.jobs.personio.de for any open opportunities with Lisk in the future.
> 
> Best regards, Sameer

Thank you for reaching out me
could you share your discord ID for better communication
